"""add training data to company

Revision ID: 748df60fac2d
Revises: None
Create Date: 2026-05-11 07:34:00.689732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '748df60fac2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('chunks_fa57414b_4a44_40f6_a5b9_1f62394f26d2_idx_1'), table_name='data_chunks_fa57414b_4a44_40f6_a5b9_1f62394f26d2')
    op.drop_index(op.f('data_chunks_fa57414b_4a44_40f6_a5b9_1f62394f26d2_embedding_idx'), table_name='data_chunks_fa57414b_4a44_40f6_a5b9_1f62394f26d2', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_table('data_chunks_fa57414b_4a44_40f6_a5b9_1f62394f26d2')
    op.add_column('company_registrations', sa.Column('team_size', sa.String(length=32), nullable=True))
    op.add_column('company_registrations', sa.Column('monthly_volume', sa.String(length=32), nullable=True))
    
    # Fix: Add channels as nullable first to handle existing rows
    op.add_column('company_registrations', sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("UPDATE company_registrations SET channels = '[]'")
    op.alter_column('company_registrations', 'channels', nullable=False)

    op.add_column('company_registrations', sa.Column('training_data', sa.Text(), nullable=True))
    
    # Fix: Truncate document_chunks because 1536-dim vectors cannot be converted to 768-dim
    op.execute("TRUNCATE TABLE document_chunks")
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False)
    op.drop_column('company_registrations', 'training_data')
    op.drop_column('company_registrations', 'channels')
    op.drop_column('company_registrations', 'monthly_volume')
    op.drop_column('company_registrations', 'team_size')
    op.create_table('data_chunks_fa57414b_4a44_40f6_a5b9_1f62394f26d2',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_chunks_fa57414b_4a44_40f6_a5b9_1f62394f26d2_pkey'))
    )
    op.create_index(op.f('data_chunks_fa57414b_4a44_40f6_a5b9_1f62394f26d2_embedding_idx'), 'data_chunks_fa57414b_4a44_40f6_a5b9_1f62394f26d2', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('chunks_fa57414b_4a44_40f6_a5b9_1f62394f26d2_idx_1'), 'data_chunks_fa57414b_4a44_40f6_a5b9_1f62394f26d2', [sa.literal_column("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    # ### end Alembic commands ###